import { useAuth } from "@clerk/expo";
import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "expo-router";
import * as Haptics from "expo-haptics";
import {
  View,
  Text,
  TextInput,
  Pressable,
  StyleSheet,
  FlatList,
  ActivityIndicator,
  Animated,
} from "react-native";
import { GestureHandlerRootView, Swipeable } from "react-native-gesture-handler";
import { RefreshCw } from "lucide-react-native";
import {
  suggestRecipes,
  getSavedRecipes,
  submitRecipeFeedback,
  getRecipeFeedback,
  type RecipeResponse,
  type SavedRecipeResponse,
  type FeedbackItem,
} from "../../lib/api";
import { colors, fonts, type as typ, radii, shadows, layout } from "../../lib/theme";
import { Card } from "../../components/Card";
import { Tag } from "../../components/Tag";
import { Chip } from "../../components/Chip";
import { Button } from "../../components/Button";

const FILTERS = ["For you", "Saved"] as const;
type Filter = (typeof FILTERS)[number];

const LOADING_STAGES = [
  "Analysing your kitchen...",
  "Cooking up recipes...",
  "Finishing touches...",
];

// Module-level cache so recipes survive tab unmount/remount
let cachedRecipes: RecipeResponse[] = [];
let cachedHasGenerated = false;

export default function RecipesScreen() {
  const router = useRouter();
  const { getToken, sessionId } = useAuth();
  const getTokenRef = useRef(getToken);
  getTokenRef.current = getToken;

  const [recipes, setRecipesState] = useState<RecipeResponse[]>(cachedRecipes);
  const [saved, setSaved] = useState<SavedRecipeResponse[]>([]);
  const [loading, setLoading] = useState(false);
  const [hasGenerated, setHasGeneratedState] = useState(cachedHasGenerated);
  const [filter, setFilter] = useState<Filter>("For you");
  const [query, setQuery] = useState("");
  const [searching, setSearching] = useState(false);
  const [feedbackMap, setFeedbackMap] = useState<Record<string, "like" | "dislike">>({});
  const [refreshingIndex, setRefreshingIndex] = useState<number | null>(null);

  // Sync state setters with module-level cache
  function setRecipes(updater: RecipeResponse[] | ((prev: RecipeResponse[]) => RecipeResponse[])) {
    setRecipesState((prev) => {
      const next = typeof updater === "function" ? updater(prev) : updater;
      cachedRecipes = next;
      return next;
    });
  }
  function setHasGenerated(val: boolean) {
    cachedHasGenerated = val;
    setHasGeneratedState(val);
  }

  // Loading animation
  const [loadingStage, setLoadingStage] = useState(0);
  const progressAnim = useRef(new Animated.Value(0)).current;
  const stageTimers = useRef<ReturnType<typeof setTimeout>[]>([]);
  const hasAutoGenerated = useRef(cachedHasGenerated);

  useEffect(() => {
    return () => { stageTimers.current.forEach(clearTimeout); };
  }, []);

  // Auto-generate once session is ready
  useEffect(() => {
    if (sessionId && !hasAutoGenerated.current && !loading && !hasGenerated) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, [sessionId]);

  useEffect(() => {
    async function loadSaved() {
      try {
        const token = await getTokenRef.current();
        if (!token) return;
        const [savedData, feedbackData] = await Promise.all([
          getSavedRecipes(token),
          getRecipeFeedback(token),
        ]);
        setSaved(savedData.recipes);
        const map: Record<string, "like" | "dislike"> = {};
        feedbackData.feedback.forEach((f: FeedbackItem) => { map[f.recipeTitle] = f.feedback; });
        setFeedbackMap(map);
      } catch { /* ignore */ }
    }
    if (sessionId) loadSaved();
  }, [sessionId]);

  function startLoadingAnimation() {
    stageTimers.current.forEach(clearTimeout);
    stageTimers.current = [];
    setLoadingStage(0);
    progressAnim.setValue(0);

    Animated.timing(progressAnim, {
      toValue: 0.35, duration: 1500, useNativeDriver: false,
    }).start();

    stageTimers.current.push(
      setTimeout(() => {
        setLoadingStage(1);
        Animated.timing(progressAnim, {
          toValue: 0.7, duration: 3000, useNativeDriver: false,
        }).start();
      }, 1500)
    );

    stageTimers.current.push(
      setTimeout(() => {
        setLoadingStage(2);
        Animated.timing(progressAnim, {
          toValue: 0.9, duration: 4000, useNativeDriver: false,
        }).start();
      }, 5000)
    );
  }

  function finishLoadingAnimation() {
    stageTimers.current.forEach(clearTimeout);
    stageTimers.current = [];
    Animated.timing(progressAnim, {
      toValue: 1, duration: 300, useNativeDriver: false,
    }).start();
  }

  async function handleGenerate() {
    setLoading(true);
    startLoadingAnimation();
    try {
      const token = await getTokenRef.current();
      if (!token) return;
      const data = await suggestRecipes(token);
      finishLoadingAnimation();
      await new Promise((r) => setTimeout(r, 400));
      setRecipes(data.recipes);
      setHasGenerated(true);
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch { /* ignore */ } finally {
      setLoading(false);
      setLoadingStage(0);
      progressAnim.setValue(0);
    }
  }

  async function handleRefreshRecipe(index: number) {
    setRefreshingIndex(index);
    try {
      const token = await getTokenRef.current();
      if (!token) return;
      const exclude = recipes.map((r) => r.title);
      const data = await suggestRecipes(token, { count: 1, exclude });
      if (data.recipes.length > 0) {
        setRecipes((prev) => prev.map((r, i) => (i === index ? data.recipes[0] : r)));
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      }
    } catch { /* ignore */ } finally {
      setRefreshingIndex(null);
    }
  }

  async function handleFeedback(title: string, type: "like" | "dislike") {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    const previous = feedbackMap[title];
    setFeedbackMap((prev) => {
      const next = { ...prev };
      if (previous === type) delete next[title];
      else next[title] = type;
      return next;
    });
    try {
      const token = await getTokenRef.current();
      if (!token) return;
      await submitRecipeFeedback(token, title, type);
    } catch {
      setFeedbackMap((prev) => {
        const next = { ...prev };
        if (previous) next[title] = previous;
        else delete next[title];
        return next;
      });
    }
  }

  async function handleIngredientSearch() {
    const trimmed = query.trim();
    if (!trimmed) return;
    setSearching(true);
    setFilter("For you");
    startLoadingAnimation();
    setLoading(true);
    try {
      const token = await getTokenRef.current();
      if (!token) return;
      const data = await suggestRecipes(token, { ingredient: trimmed });
      finishLoadingAnimation();
      await new Promise((r) => setTimeout(r, 400));
      setRecipes(data.recipes);
      setHasGenerated(true);
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch { /* ignore */ } finally {
      setLoading(false);
      setSearching(false);
      setLoadingStage(0);
      progressAnim.setValue(0);
    }
  }

  // Filter + search logic
  const allRecipes: (RecipeResponse | SavedRecipeResponse)[] =
    filter === "Saved" ? saved : recipes;

  const filtered = allRecipes;

  function openDetail(recipe: RecipeResponse | SavedRecipeResponse) {
    router.push({
      pathname: "/recipe-detail",
      params: { recipe: JSON.stringify(recipe) },
    });
  }

  function renderSwipeAction(index: number) {
    return (
      <Pressable
        style={styles.refreshAction}
        onPress={() => handleRefreshRecipe(index)}
      >
        {refreshingIndex === index ? (
          <ActivityIndicator size="small" color={colors.bg} />
        ) : (
          <>
            <RefreshCw size={18} strokeWidth={2.75} color={colors.bg} />
            <Text style={styles.refreshActionText}>Refresh</Text>
          </>
        )}
      </Pressable>
    );
  }

  function renderCard({
    item,
    index,
  }: {
    item: RecipeResponse | SavedRecipeResponse;
    index: number;
  }) {
    const inKitchen = item.ingredients.filter((i) => i.inPantry).length;
    const needMore = item.ingredients.filter((i) => !i.inPantry).length;

    const cardContent = (
      <Pressable onPress={() => openDetail(item)}>
        <Card elevation="sm" style={styles.recipeCard}>
          <Text style={styles.cardTitle}>{item.title}</Text>
          <Text style={styles.cardMeta}>
            {item.cookTime} · {item.difficulty} · {item.servings} servings
          </Text>
          <View style={styles.cardTags}>
            <Tag
              label={`${inKitchen} in your kitchen`}
              variant="accent2"
            />
            <Tag
              label={needMore > 0 ? `Need ${needMore} more` : "You have everything"}
              variant={needMore > 0 ? "accent" : "accent2"}
            />
          </View>
        </Card>
      </Pressable>
    );

    if (filter !== "Saved") {
      return (
        <Swipeable
          renderLeftActions={() => renderSwipeAction(index)}
          overshootLeft={false}
        >
          {cardContent}
        </Swipeable>
      );
    }

    return cardContent;
  }

  if (loading) {
    return (
      <View style={[styles.container, styles.center]}>
        <Text style={styles.loadingText}>{LOADING_STAGES[loadingStage]}</Text>
        <View style={styles.progressBg}>
          <Animated.View
            style={[
              styles.progressFill,
              {
                width: progressAnim.interpolate({
                  inputRange: [0, 1],
                  outputRange: ["0%", "100%"],
                }),
              },
            ]}
          />
        </View>
      </View>
    );
  }

  return (
    <GestureHandlerRootView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Recipes</Text>

        {/* Ingredient search — submit to generate recipes */}
        <TextInput
          value={query}
          onChangeText={setQuery}
          onSubmitEditing={handleIngredientSearch}
          placeholder="Generate recipes with an ingredient..."
          placeholderTextColor={colors.neutral[500]}
          style={styles.searchInput}
          returnKeyType="search"
        />

        {/* Filter chips */}
        <View style={styles.filterRow}>
          {FILTERS.map((f) => (
            <Chip
              key={f}
              label={f}
              selected={filter === f}
              onPress={() => setFilter(f)}
              style={{ flex: 1, alignItems: "center" }}
            />
          ))}
        </View>
      </View>

      {!hasGenerated && filtered.length === 0 ? (
        <View style={styles.center}>
          <Text style={styles.emptyTitle}>Nothing on that shelf yet</Text>
          <Text style={styles.emptyBody}>
            Try another filter — or clear the search.
          </Text>
        </View>
      ) : (
        <FlatList
          data={filtered}
          keyExtractor={(item, i) =>
            "id" in item ? String(item.id) : `${item.title}-${i}`
          }
          renderItem={renderCard}
          contentContainerStyle={styles.listContent}
          ListFooterComponent={
            filter !== "Saved" && hasGenerated ? (
              <View style={styles.regenerateFooter}>
                <Button
                  title="Regenerate recipes"
                  onPress={handleGenerate}
                />
              </View>
            ) : null
          }
        />
      )}
    </GestureHandlerRootView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  header: {
    paddingTop: 66,
    paddingHorizontal: layout.screenGutter,
    paddingBottom: 8,
  },
  title: {
    ...typ.h2,
    color: colors.text,
    marginBottom: 6,
  },
  searchInput: {
    minHeight: 48,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: radii.pill,
    paddingHorizontal: 18,
    fontFamily: fonts.body,
    fontSize: 14,
    color: colors.text,
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  // Loading
  loadingText: {
    ...typ.h4,
    color: colors.text,
    marginBottom: 20,
  },
  progressBg: {
    width: "80%",
    height: 6,
    backgroundColor: colors.neutral[300],
    borderRadius: radii.pill,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors.cta.DEFAULT,
    borderRadius: radii.pill,
  },
  // List
  listContent: {
    paddingHorizontal: layout.screenGutter,
    paddingBottom: 40,
  },
  regenerateFooter: {
    marginTop: 8,
    marginBottom: 16,
  },
  recipeCard: {
    padding: 16,
    paddingHorizontal: 18,
    marginBottom: 10,
    gap: 7,
  },
  cardTitle: {
    ...typ.cardTitle,
    color: colors.text,
  },
  cardMeta: {
    fontFamily: fonts.body,
    fontSize: 11,
    lineHeight: 14,
    color: "rgba(32, 30, 29, 0.5)",
  },
  cardTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  // Swipe refresh
  refreshAction: {
    backgroundColor: colors.cta.DEFAULT,
    justifyContent: "center",
    alignItems: "center",
    width: 80,
    marginBottom: 10,
    borderRadius: radii.card,
  },
  refreshActionText: {
    fontFamily: fonts.body,
    color: colors.bg,
    fontSize: 12,
    marginTop: 4,
  },
  // Empty
  emptyTitle: {
    ...typ.h4,
    color: colors.text,
    marginBottom: 8,
    textAlign: "center",
  },
  emptyBody: {
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 22,
    color: colors.neutral[600],
    textAlign: "center",
  },
});
